# Generated by Django 2.2.9 on 2020-01-13 17:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20200113_1744'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='residents',
            new_name='resident',
        ),
    ]
