# Generated by Django 2.2.9 on 2020-01-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200113_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='id',
        ),
        migrations.AlterField(
            model_name='resident',
            name='veh_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
