# Generated by Django 2.2.9 on 2020-01-13 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200113_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='in_time',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='out_time',
        ),
    ]
