# Generated by Django 2.2.9 on 2020-01-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200121_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifiy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(max_length=100)),
            ],
        ),
    ]
